curry_company: # Nome do perfil (deve bater com o 'profile' no dbt_project.yml)
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: curry-company-494501
      dataset: curry_company # O dataset principal onde as tabelas finais vão morar
      threads: 4
      timeout_seconds: 300
      location: us-central1 # Mesma região que você criou o dataset